title: ConstraintLayout
url: https://constraintlayout.com
defaults:
  -
    scope:
     path: ""
    values:
      index: true
  -
    scope:
      path: "contributors"
    values:
      index: false
